export const SIGNALS_FETCHED = 'SIGNALS_FETCHED'
export const SIGNAL_NAME_ADDED = 'SIGNAL_NAME_ADDED'
export const SIGNAL_NAME_DELETED = 'SIGNAL_NAME_DELETED'
export const SIGNAL_NAMES_FETCHED = 'SIGNAL_NAMES_FETCHED'

export const SUMMARY_FETCHED = 'SUMMARY_FETCHED'
export const SUMMARY_SAVED = 'SUMMARY_SAVED'

export const INSIGHT_FETCHED = 'INSIGHT_FETCHED'

export const LOGIN_STATE_FETCHED = 'LOGIN_STATE_FETCHED'
export const LOGOUT = 'LOGOUT'

export const GOAL_ADDED = 'GOAL_ADDED'
export const GOAL_FETCHED = 'GOAL_FETCHED'
export const GOAL_DELETE_SUCCESS = 'GOAL_DELETE_SUCCESS'
export const GOALS_FETCHED = 'GOALS_FETCHED'
export const REPORTS_FETCHED = 'REPORTS_FETCHED'
export const REPORT_SAVE_SUCCESS = 'REPORT_SAVE_SUCCESS'
export const REPORT_DELETE_SUCCESS = 'REPORT_DELETE_SUCCESS'